# -*- coding: utf-8 -*-
"""hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kE4n55mB0gSaXixcqwqLGv6JTbmq6eih
"""

class rate_calculator:
  def __init__ (self,price,coupon_rate=0.05,par_value=100):
    self.spot=[]
    self.forward=[['-'] * len(price)for i in range(len(price))]
    self.ytm=[]
    for i in range(len(price)):
      self.ytm.append(round(pow((((i+1)*coupon_rate+1)*par_value)/price[i],1/(i+1))-1,3))
    for i in range(len(price)):
      if i == 0 :
        self.spot.append(self.ytm[0])
      else :
        for j in range(i):
          price[i] -= coupon_rate*par_value/(1+self.spot[j])
        self.spot.append(round(pow(((coupon_rate+1)*par_value)/price[i],1/(i+1))-1,3))
    for i in range(len(price)):
      for j in range(len(price)):
        if i < j : 
          self.forward[i][j]=\
          round(pow(((1+self.spot[j])**(j+1))/((1+self.spot[i])**(i+1)),1/(j-i))-1,3)
  def getforward(self,x,y):
    return self.forward[x][y]
  def getspot(self,y):
    return self.spot[y]
  def getytm(self,m):
    return self.ytm[m]

while True:
  price_s = input('Input the price sequence (per years):')
  price_t = []
  for prices in price_s.split(','):
    price_t.append(float(prices))
  r=rate_calculator(price_t,float(input('Input the Coupon rate(%):'))/100,\
                float(input('Input the Par value:')))
  task = input('Key one of (spot rate , forward rate , YTM) :')
  if task == 'spot rate':
    print(r.getspot(int(input('which year ? :'))-1))
  if task == 'forward rate':
    print('Please key the indexs i , j with i < j')
    print(r.getforward(int(input('i index :'))-1,int(input('j index :'))-1))
  if task == 'YTM':
    print(r.getytm(int(input('which year ? :'))-1))
  if input("Key quit to quit :")=='quit':break